//! arm64 entry point: 7-Zip's `Asm/arm64/LzmaDecOpt.S`, preprocessed.
//!
//! `src/asm/lzma_dec_opt_arm64.s` is generated by `scripts/gen-lzma-dec-asm.sh`
//! from the vendored upstream files (see `src/asm/README.md`). The assembly
//! saves x19..x30 on its own 128-byte frame and never touches x18.

use core::arch::{asm, global_asm};

use super::common::CLzmaDec;

global_asm!(
    ".text",
    ".p2align 4,,15",
    concat!(".globl ", decode_real_sym!()),
    visibility!(),
    concat!(decode_real_sym!(), ":"),
    // BTI landing pad; a NOP on cores without branch target identification.
    "hint #34",
    include_str!("../asm/lzma_dec_opt_arm64.s"),
    decode_real_symbol_prefix = sym super::DECODE_REAL_SYMBOL_PREFIX,
);

/// Calls 7-Zip's `LzmaDec_DecodeReal_3`.
///
/// # Safety
///
/// Every precondition in the [`common`](super::common) module documentation
/// must hold: `p` points to a struct whose `probs`, `dic` and `buf` pointers
/// are valid for the sizes implied by `lc + lp`, `dic_buf_size` and
/// `buf_limit + 20`, and no Rust reference to those buffers is used while the
/// call runs.
#[inline(always)]
pub(crate) unsafe fn decode_real(p: *mut CLzmaDec, limit: usize, buf_limit: *const u8) -> u32 {
    let ret: u64;
    // SAFETY: plain AAPCS64 call. The callee preserves x19..x30 (it saves them
    // on its own frame) and touches only memory reachable from `p`, which the
    // caller guarantees to be valid.
    unsafe {
        asm!(
            concat!("bl ", decode_real_sym!()),
            inout("x0") p as u64 => ret,
            in("x1") limit,
            in("x2") buf_limit,
            decode_real_symbol_prefix = sym super::DECODE_REAL_SYMBOL_PREFIX,
            clobber_abi("C"),
        );
    }
    ret as u32
}
