//! x86-64 entry point: 7-Zip's `Asm/x86/LzmaDecOpt.asm`, translated from
//! MASM to GNU as Intel syntax for the System V ABI.
//!
//! `src/asm/lzma_dec_opt_x86_64.s` is generated by
//! `scripts/gen-lzma-dec-asm-x86_64.sh` from the vendored upstream files (see
//! `src/asm/README.md`). The routine takes its arguments in rdi / rsi / rdx,
//! returns in eax, saves rbx, rbp and r12..r15 on its own frame and realigns
//! the stack to 128 bytes for its locals, restoring it before `ret`.
//!
//! Windows is not supported: the Win64 calling convention passes arguments in
//! other registers and requires rsi / rdi to be preserved, and unwinding
//! through the realigned frame would need `.seh_*` directives.

use core::arch::{asm, global_asm};

use super::common::CLzmaDec;

global_asm!(
    ".text",
    // Upstream assembles the routine into a 64-byte aligned segment.
    ".p2align 6",
    concat!(".globl ", decode_real_sym!()),
    visibility!(),
    concat!(decode_real_sym!(), ":"),
    // IBT landing pad; a NOP on cores without CET.
    "endbr64",
    include_str!("../asm/lzma_dec_opt_x86_64.s"),
    decode_real_symbol_prefix = sym super::decode_real_symbol_prefix,
);

/// Calls 7-Zip's `LzmaDec_DecodeReal_3`.
///
/// # Safety
///
/// Every precondition in the [`common`](super::common) module documentation
/// must hold: `p` points to a struct whose `probs`, `dic` and `buf` pointers
/// are valid for the sizes implied by `lc + lp`, `dic_buf_size` and
/// `buf_limit + 20`, and no Rust reference to those buffers is used while the
/// call runs.
#[inline(always)]
pub(crate) unsafe fn decode_real(p: *mut CLzmaDec, limit: usize, buf_limit: *const u8) -> u32 {
    let ret: u32;
    // SAFETY: plain System V call. The callee saves rbx, rbp and r12..r15 on
    // its own frame, every other register is covered by `clobber_abi`, and it
    // touches only memory reachable from `p`, which the caller guarantees to
    // be valid. Without `nostack` the stack is 16-byte aligned here and the
    // red zone is free, as a `call` requires.
    unsafe {
        asm!(
            concat!("call ", decode_real_sym!()),
            in("rdi") p,
            in("rsi") limit,
            in("rdx") buf_limit,
            out("eax") ret,
            decode_real_symbol_prefix = sym super::decode_real_symbol_prefix,
            clobber_abi("sysv64"),
        );
    }
    ret
}
